In [1]:
# Import the libraries

import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [4]:
# Convert list to Numpy Array
# Every element is the same type

A = np. array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
# Show the numpy array dimensions

A.ndim

2

In [6]:
# Show the numpy array shape

A.shape

(3, 3)

In [7]:
# Show the numpy array size

A.size

9

In [8]:
# Access the element on the second row and third column

A[1,2]

23

In [9]:
# Access the element on the second row and third column

A[1][2]

23

In [10]:
# Access the element on the first row and first column

A[0][0]

11

In [11]:
# Access the element on the first row and first and second column

A[0][0:2]

array([11, 12])

In [14]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

In [15]:
# Create a numpy array x

X = np.array([[1,0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [17]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [18]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [19]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [20]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [21]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [22]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [23]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [24]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [25]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [26]:
# Calculate the dot product

Z = np.dot(A, B)
Z

array([[0, 2],
       [0, 2]])

In [27]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [28]:
# Create a matrix C

C = np.array([[1, 1], [2, 2], [3, 3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [29]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [30]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10 , 11, 12]]

A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
A.size

12

In [32]:
A[0,1]

2

In [33]:
A [0][0:2]

array([1, 2])

In [35]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
B

array([[ 0,  1],
       [ 1,  0],
       [ 1,  1],
       [-1,  0]])

In [39]:
A = np.dot
A

<function numpy.dot>

In [42]:
B = np.array([[0, 1], [1, 0], [-1, 0]])
B

array([[ 0,  1],
       [ 1,  0],
       [-1,  0]])